name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  RUBY_VERSION: 3.0
  SIMPLECOV_THRESHOLD: 100

jobs:
  tests_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run tests checker
        run: ruby -r "./ci/tests_checker.rb" -e "::CI::TestsChecker.new.process"

  links_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run links checker
        run: ruby -r "./ci/links_checker.rb" -e "::CI::LinksChecker.new.process"

  version_checker:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run version checker
        run: ruby -r "./ci/version_checker.rb" -e "::CI::VersionChecker.new.process"

  readme_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run README checker
        run: ruby -r "./ci/readme_checker.rb" -e "::CI::ReadmeChecker.new.process"

  last_reachable_checker:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run last reachable checker
        run: ruby -r "./ci/last_reachable_checker.rb" -e "::CI::LastReachableChecker.new.process"

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rake rubocop

  tests:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test
      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          failedThreshold: ${{ env.SIMPLECOV_THRESHOLD }}
